---
deployment:
  tasks:
    - export DEPLOY=/home/xappsqsm/public_html/udh-pl/wp-content/themes
    - export REPO=udh-pl-wp-theme
    - rm -R $DEPLOY/$REPO
    - cp -R * $DEPLOY
    - rm -R $DEPLOY/$REPO/.git
    - rm -R $DEPLOY/$REPO/tmp
    - rm $DEPLOY/$REPO/.gitignore