---
deployment:
  tasks:
    - export DEPLOY=/home/xappsqsm/public_html/udh-pl/wp-content/themes
    - export REPO=$(basename $PWD)
    - if [ ! -d $DEPLOY/$REPO ]; then mkdir $DEPLOY/$REPO else rm -rf $DEPLOY/$REPO fi
    - cp -r * $DEPLOY/$REPO